block-beta
    block
          columns 2
          uc("User code"):2
          block
            columns 1
            k("Karibu DSL")
            v("Vaadin Flow")
          end
          sb("Spring Boot")
    end
style sb fill: #6db33f
style v fill: #1e9cd9
style k fill: #5dbbe9
